import Mathlib.Topology.Instances.AddCircle.DenseSubgroup
import Mathlib.Analysis.SpecialFunctions.Log.Basic
import Mathlib.Algebra.Group.Subgroup.Lattice
import Mathlib.Tactic

open Filter Set

namespace XiGap

/-- Multiplicative independence of positive real numbers implies an irrational log ratio. -/
theorem irrational_log_div_of_pow_ne {a b : ℝ} (ha : 1 < a) (hb : 1 < b)
    (hind : ∀ m n : ℕ, 0 < m → 0 < n → a ^ m ≠ b ^ n) :
    Irrational (Real.log a / Real.log b) := by
  rintro ⟨q, hq⟩
  have hla : 0 < Real.log a := Real.log_pos ha
  have hlb : 0 < Real.log b := Real.log_pos hb
  have hqpos : 0 < q := by
    have h : (0 : ℝ) < q := by rw [hq]; exact div_pos hla hlb
    exact_mod_cast h
  have hnpos : 0 < q.num := Rat.num_pos.mpr hqpos
  have hnc : (q.num.natAbs : ℝ) = (q.num : ℝ) := by
    simpa only [Nat.cast_natAbs, Int.cast_abs] using
      abs_of_pos (show (0 : ℝ) < q.num by exact_mod_cast hnpos)
  have hd0 : (q.den : ℝ) ≠ 0 := by exact_mod_cast q.den_ne_zero
  have heq : (q.den : ℝ) * Real.log a = (q.num.natAbs : ℝ) * Real.log b := by
    rw [Rat.cast_def] at hq
    have h := (div_eq_div_iff hd0 (ne_of_gt hlb)).mp hq
    rw [← hnc] at h
    linarith
  have hpow : a ^ q.den = b ^ q.num.natAbs := by
    have h := congrArg Real.exp heq
    simpa only [Real.exp_nat_mul, Real.exp_log (lt_trans zero_lt_one ha),
      Real.exp_log (lt_trans zero_lt_one hb)] using h
  exact hind q.den q.num.natAbs q.den_pos (by omega) hpow

/-- Coprime natural generators greater than one have irrational log ratio. -/
theorem irrational_log_div_of_coprime {a b : ℕ} (ha : 1 < a) (hb : 1 < b)
    (hab : a.Coprime b) : Irrational (Real.log (a : ℝ) / Real.log (b : ℝ)) := by
  apply irrational_log_div_of_pow_ne (by exact_mod_cast ha) (by exact_mod_cast hb)
  intro m n hm hn hp
  have hpn : a ^ m = b ^ n := by exact_mod_cast hp
  have hc : (a ^ m).Coprime (b ^ n) := hab.pow m n
  rw [hpn] at hc
  have heq : b ^ n = 1 := by simpa [Nat.Coprime] using hc
  have hgt : 1 < b ^ n := one_lt_pow₀ hb (ne_of_gt hn)
  omega

/-- The additive semigroup generated by two real numbers, including zero. -/
def IsAddIndex (a b x : ℝ) : Prop := ∃ i j : ℕ, x = i * a + j * b

lemma isAddIndex_add {a b x y : ℝ} (hx : IsAddIndex a b x)
    (hy : IsAddIndex a b y) : IsAddIndex a b (x + y) := by
  rcases hx with ⟨i, j, rfl⟩
  rcases hy with ⟨k, l, rfl⟩
  refine ⟨i + k, j + l, ?_⟩
  push_cast
  ring

lemma isAddIndex_nat_mul {a b x : ℝ} (hx : IsAddIndex a b x) (n : ℕ) :
    IsAddIndex a b (n * x) := by
  rcases hx with ⟨i, j, rfl⟩
  refine ⟨n * i, n * j, ?_⟩
  push_cast
  ring

lemma exists_small_difference {a b ε : ℝ} (hirr : Irrational (a / b))
    (hε : 0 < ε) :
    ∃ u v : ℝ, IsAddIndex a b u ∧ IsAddIndex a b v ∧ 0 < u - v ∧ u - v < ε := by
  have hd : Dense (AddSubgroup.closure {a, b} : Set ℝ) :=
    dense_addSubgroupClosure_pair_iff.mpr hirr
  obtain ⟨δ, hδ, hδpos, hδlt⟩ := hd.exists_between hε
  obtain ⟨i, j, hij⟩ := AddSubgroup.mem_closure_pair.mp hδ
  have hcast : ∀ z : ℤ,
      (z : ℝ) = (z.toNat : ℝ) - ((-z).toNat : ℝ) := by
    intro z
    have h : z = (z.toNat : ℤ) - ((-z).toNat : ℤ) := by omega
    exact_mod_cast h
  let u : ℝ := (i.toNat : ℝ) * a + (j.toNat : ℝ) * b
  let v : ℝ := ((-i).toNat : ℝ) * a + ((-j).toNat : ℝ) * b
  have huv : u - v = δ := by
    rw [← hij]
    simp only [zsmul_eq_mul]
    rw [hcast i, hcast j]
    dsimp [u, v]
    ring
  exact ⟨u, v, ⟨i.toNat, j.toNat, rfl⟩, ⟨(-i).toNat, (-j).toNat, rfl⟩,
    huv ▸ hδpos, huv ▸ hδlt⟩

/-- Every late additive interval of fixed positive length meets the positive semigroup. -/
theorem eventually_exists_nat_mul_add_mem_Ioc {a b ε : ℝ}
    (hb : 0 < b) (hirr : Irrational (a / b)) (hε : 0 < ε) :
    ∀ᶠ x : ℝ in atTop, ∃ i j : ℕ, x < i * a + j * b ∧ i * a + j * b ≤ x + ε := by
  obtain ⟨u, v, hu, hv, hδpos, hδlt⟩ := exists_small_difference hirr hε
  let δ := u - v
  have hdpos : 0 < δ := hδpos
  obtain ⟨K, hK⟩ := exists_nat_gt (b / δ + 1)
  let R : ℝ := (K : ℝ) * v
  filter_upwards [eventually_ge_atTop R] with x hx
  let n : ℕ := ⌊(x - R) / b⌋₊
  have hnlo : (n : ℝ) * b ≤ x - R := by
    have h := Nat.floor_le (div_nonneg (sub_nonneg.mpr hx) hb.le)
    exact (le_div_iff₀ hb).mp h
  have hnhi : x - R < ((n : ℝ) + 1) * b := by
    have h := Nat.lt_floor_add_one ((x - R) / b)
    exact (div_lt_iff₀ hb).mp h
  let r : ℝ := x - R - (n : ℝ) * b
  have hrpos : 0 ≤ r := sub_nonneg.mpr hnlo
  have hrlt : r < b := by dsimp [r]; nlinarith
  let m : ℕ := ⌊r / δ⌋₊ + 1
  have hmlo : r < (m : ℝ) * δ := by
    have h := Nat.lt_floor_add_one (r / δ)
    have hc : (m : ℝ) = (⌊r / δ⌋₊ : ℝ) + 1 := by simp [m]
    rw [← hc] at h
    exact (div_lt_iff₀ hdpos).mp h
  have hmhi : (m : ℝ) * δ ≤ r + δ := by
    have h := Nat.floor_le (div_nonneg hrpos hdpos.le)
    have hc : (m : ℝ) = (⌊r / δ⌋₊ : ℝ) + 1 := by simp [m]
    have ht := (le_div_iff₀ hdpos).mp h
    rw [hc]
    nlinarith
  have hmK : m ≤ K := by
    have h1 : (m : ℝ) ≤ r / δ + 1 := by
      have h := Nat.floor_le (div_nonneg hrpos hdpos.le)
      simpa [m] using add_le_add_right h 1
    have h2 : r / δ < b / δ := (div_lt_div_iff_of_pos_right hdpos).mpr hrlt
    have h3 : (m : ℝ) < K := by linarith
    exact_mod_cast h3.le
  have hy : IsAddIndex a b ((K : ℝ) * v + (n : ℝ) * b + (m : ℝ) * δ) := by
    have hleft := isAddIndex_add (isAddIndex_nat_mul hv (K - m))
      (isAddIndex_nat_mul hu m)
    have hright : IsAddIndex a b ((n : ℝ) * b) := ⟨0, n, by simp⟩
    have hsum := isAddIndex_add hleft hright
    convert hsum using 1 <;> push_cast [Nat.cast_sub hmK] <;> dsimp [δ] <;> ring
  obtain ⟨i, j, hij⟩ := hy
  refine ⟨i, j, ?_, ?_⟩
  · rw [← hij]
    dsimp [r] at hmlo
    dsimp [R] at hmlo
    linarith
  · rw [← hij]
    dsimp [r] at hmhi
    dsimp [R] at hmhi
    dsimp [δ] at hmhi
    dsimp [δ]
    linarith

/-- Two multiplicatively independent positive generators have vanishing relative gaps. -/
theorem eventually_exists_pow_mul_mem_Ioc {a b ε : ℝ}
    (ha : 1 < a) (hb : 1 < b)
    (hirr : Irrational (Real.log a / Real.log b)) (hε : 0 < ε) :
    ∀ᶠ x : ℝ in atTop, ∃ i j : ℕ, x < a ^ i * b ^ j ∧
      a ^ i * b ^ j ≤ (1 + ε) * x := by
  have ha0 : 0 < a := lt_trans zero_lt_one ha
  have hb0 : 0 < b := lt_trans zero_lt_one hb
  have he0 : 0 < 1 + ε := by linarith
  have he1 : 1 < 1 + ε := by linarith
  have h := eventually_exists_nat_mul_add_mem_Ioc (Real.log_pos hb) hirr
    (Real.log_pos he1)
  filter_upwards [Real.tendsto_log_atTop.eventually h, eventually_gt_atTop (0 : ℝ)]
    with x hx hx0
  obtain ⟨i, j, hlo, hhi⟩ := hx
  refine ⟨i, j, ?_, ?_⟩
  · have h' := Real.exp_lt_exp.mpr hlo
    simpa [Real.exp_add, Real.exp_nat_mul, Real.exp_log ha0,
      Real.exp_log hb0, Real.exp_log hx0] using h'
  · have h' := Real.exp_le_exp.mpr hhi
    simpa [Real.exp_add, Real.exp_nat_mul, Real.exp_log ha0,
      Real.exp_log hb0, Real.exp_log hx0, Real.exp_log he0, mul_comm] using h'

/-- The relative-gap conclusion is uniform after a moving positive dilation,
provided the remaining scale tends to infinity. -/
theorem eventually_exists_dilated_pow_mul_mem_Ioc {ι : Type*} {l : Filter ι}
    {a b ε : ℝ} (ha : 1 < a) (hb : 1 < b)
    (hirr : Irrational (Real.log a / Real.log b)) (hε : 0 < ε)
    {N t : ι → ℝ} (ht : ∀ᶠ z in l, 0 < t z)
    (hscale : Tendsto (fun z => N z / t z) l atTop) :
    ∀ᶠ z in l, ∀ x : ℝ, N z ≤ x → ∃ i j : ℕ,
      x < t z * (a ^ i * b ^ j) ∧ t z * (a ^ i * b ^ j) ≤ (1 + ε) * x := by
  obtain ⟨M, hM⟩ := eventually_atTop.mp
    (eventually_exists_pow_mul_mem_Ioc ha hb hirr hε)
  filter_upwards [ht, hscale.eventually (eventually_ge_atTop M)] with z htz hNz
  intro x hx
  have hxM : M ≤ x / t z := hNz.trans ((div_le_div_iff_of_pos_right htz).mpr hx)
  obtain ⟨i, j, hlo, hhi⟩ := hM (x / t z) hxM
  refine ⟨i, j, ?_, ?_⟩
  · have h' := (div_lt_iff₀ htz).mp hlo
    simpa [mul_comm] using h'
  · have h' := mul_le_mul_of_nonneg_right hhi htz.le
    have ht0 : t z ≠ 0 := ne_of_gt htz
    field_simp [ht0] at h'
    simpa [mul_comm, mul_left_comm, mul_assoc] using h'

/-- Natural-number form with the coprimality assumptions used by the Xi family. -/
theorem eventually_exists_nat_pow_mul_mem_Ioc {a b : ℕ} {ε : ℝ}
    (ha : 1 < a) (hb : 1 < b) (hab : a.Coprime b) (hε : 0 < ε) :
    ∀ᶠ x : ℝ in atTop, ∃ i j : ℕ,
      x < (a ^ i * b ^ j : ℕ) ∧ (a ^ i * b ^ j : ℕ) ≤ (1 + ε) * x := by
  have h := eventually_exists_pow_mul_mem_Ioc (by exact_mod_cast ha)
    (by exact_mod_cast hb) (irrational_log_div_of_coprime ha hb hab) hε
  simpa only [Nat.cast_mul, Nat.cast_pow] using h

/-- A fixed residue class in both exponents remains relatively dense after
a moving translation whose normalized scale tends to infinity. -/
theorem eventually_exists_residue_pow_mul_mem_Ioc
    {a d L i₀ : ℕ} {k : ℕ → ℕ} {ε : ℝ}
    (ha : 1 < a) (hd : 1 < d) (had : a.Coprime d) (hL : 0 < L) (hε : 0 < ε)
    (hscale : Tendsto
      (fun n : ℕ => (n : ℝ) / ((a : ℝ) ^ i₀ * (d : ℝ) ^ k n)) atTop atTop) :
    ∀ᶠ n : ℕ in atTop, ∀ x : ℝ, (n : ℝ) ≤ x → ∃ i j : ℕ,
      x < (a : ℝ) ^ (i₀ + L * i) * (d : ℝ) ^ (k n + L * j) ∧
      (a : ℝ) ^ (i₀ + L * i) * (d : ℝ) ^ (k n + L * j) ≤ (1 + ε) * x := by
  have ha0 : (0 : ℝ) < a := by exact_mod_cast (lt_trans Nat.zero_lt_one ha)
  have hd0 : (0 : ℝ) < d := by exact_mod_cast (lt_trans Nat.zero_lt_one hd)
  have haL : 1 < a ^ L := one_lt_pow₀ ha (ne_of_gt hL)
  have hdL : 1 < d ^ L := one_lt_pow₀ hd (ne_of_gt hL)
  have hirr : Irrational (Real.log ((a : ℝ) ^ L) / Real.log ((d : ℝ) ^ L)) := by
    simpa only [Nat.cast_pow] using
      irrational_log_div_of_coprime haL hdL (had.pow L L)
  have h := eventually_exists_dilated_pow_mul_mem_Ioc
    (a := (a : ℝ) ^ L) (b := (d : ℝ) ^ L)
    (N := fun n : ℕ => (n : ℝ))
    (t := fun n : ℕ => (a : ℝ) ^ i₀ * (d : ℝ) ^ k n)
    (by exact_mod_cast haL) (by exact_mod_cast hdL) hirr hε
    (Filter.Eventually.of_forall (fun n => mul_pos (pow_pos ha0 _) (pow_pos hd0 _))) hscale
  simpa only [pow_add, pow_mul, mul_assoc, mul_left_comm, mul_comm] using h

end XiGap
